repos:
  - repo: https://github.com
    rev: v4.6.0  # Use the latest version
    hooks:
      - id: check-secret-key
      - id: check-added-large-files
  - repo: https://github.com
    rev: v8.18.2
    hooks:
      - id: gitleaks
